# Game Setup
WIDTH = 1280
HEIGHT = 720
FPS = 60

# Player Settings
PLAYER_START_X = 400
PLAYER_START_Y = 500
PLAYER_SIZE = 0.2
PLAYER_SPEED = 8

# Enemy Settings
ENEMY_SPEED = 4

# Bullet Settings
SHOOT_COOLDOWN = 20
BULLET_SCALE = 0.4
BULLET_SPEED = 10